/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\gudocs-theme.ts
 * Command: astryx theme build src\theme\gudocs-theme.ts --out src\theme\gudocs-theme.css
 * Generated: 2026-07-26T03:36:50.554Z
 */

/// <reference path="./gudocs.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const gudocsTheme: DefinedTheme;
