/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\gudocs-theme.ts
 * Command: astryx theme build src\theme\gudocs-theme.ts --out src\theme\gudocs-theme.css
 * Generated: 2026-08-13T03:19:43.850Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
